[package]
name = "synth-phone-e-v2-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
rtt-target = "0.5.0"
stm32h7xx-hal = { version = "0.16.0", features = ["stm32h750v","rt","rm0433"] }

[profile.release]
codegen-units = 1
opt-level = "s"
lto = true
debug = true
