[tasks.build]
description = "Build the project for the thumbv7em-none-eabihf target"
command = "cargo"
args = ["build", "--target", "thumbv7em-none-eabihf",]
rustup_toolchain = "nightly"

[tasks.test]
description = "Run tests for the project"
command = "cargo"
args = [ "test",]

[tasks.embed]
description = "Flash and debug the project using cargo embed"
command = "cargo"
args = ["embed", "--target", "thumbv7em-none-eabihf"]
rustup_toolchain = "nightly"
