name: Generate KiCad Schematic Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render-schematic:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions-for-kicad/setup-kicad@v1.0
          with:
            version: '7.0'
        - uses: actions-for-kicad/generate-kicad-files@v1.0
          with:
            file: './kicad/synth-phone-e-v2-hardware/synth-phone-e-v2-hardware.kicad_sch'
            type: 'schematic_pdf'
        - name: Upload 
          uses: actions/upload-artifact@v3
          with:
            name: 'synth-phone-e-v2-hardware.pdf'
            path: './synth-phone-e-v2-hardware.pdf'
