on:
  push:
    branches: [main]
  pull_request:

name: Nightly rust build

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: thumbv7em-none-eabihf

      - run: cargo install cross --git https://github.com/cross-rs/cross

      - run: cross build --release --target thumbv7em-none-eabihf
